### ISSUE TITLE
5주차 : 시뮬레이션

### ISSUE THREAD

**Issue by jun108059** [Nexters/Algorithm#19]
# 5주차

## 리뷰문제

| 문제 | [시그널](https://www.acmicpc.net/problem/16113) |
|:---:|:---:|
| 출제 | [angrycatjenny](https://github.com/angrycatjenny) |
| 유형 | `Simuration` |

## 공통문제

| 문제 | [전광판의 숫자](https://www.acmicpc.net/problem/16159) |
|:---:|:---:|
| 출제 | [Minwook Je](https://github.com/minkj1992) |
| 유형 | `Simuration` |

**Comment by ricky-o-k** [comment]
시그널에서 설명했던 획 분석 내용
![image](https://user-images.githubusercontent.com/13694046/110240878-49330d00-7f91-11eb-9547-915cf7981b25.png)
