### ISSUE TITLE
map vs object in js

### ISSUE THREAD

**Issue by minkj1992** [Nexters/Algorithm#2]
@mcauto

> javascript에서 {}과 Map이랑, python에서 type이랑 isinstance랑 성능차이가 있어서 별로 확인해보고 쓰시면 좋을 것 같습니다

라는 의견에 대해 설명드리자면

구현적으로는 map이 object를 상속받아서, 적은규모 데이터의 경우에는 object가 더 우위에 있다고 생각하지만, 큰 규모의 get/set에서는 Map이 우월하고, 무엇보다 Map이 만들어진 목적 자체가,  key-value 넣고 빼는데 최적화하기 위해서 만들어졌기 때문에 더 맞는 선택이라고 생각되네요

Map Performs better than Object in scenarios involving frequent additions and removals of key-value pairs.  

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by minkj1992** [comment]
물론 map이 메모리 적인 측면에서 오버헤드가 있고, key를 넣을때 insertion order를 보존하기 때문에, 거기에 따른 오버헤드도 있다 생각되지만, 

이는 브라우저 엔진에 따라서 퍼포먼스를 추후 테스트해볼 문제라 생각되기 때문에 일반적으로 mono key:value 스토리지 역활로는 map을 사용하는게 목적상 맞을 것 같네요

추가로 object 자체가 key에 대해 string, symbol만 지원하기 때문에 key의 타입이 의도치 않게 변형될 수도 있고, object자체로 지원하는 key들을 의도치않게 수정시킬 수도 있을 것 같아요

c.f 실제로 브라우저별 퍼포먼스 부분에서 테스트 해본 유저가 있는데, [여기](https://stackoverflow.com/a/37994079) 참조

**Comment by mcauto** [comment]
넵 가독성이나 명시성측면에서는 객체를 만드는 쪽이 좋다고 생각합니다

그러나 js가 근본적으로 이상한 친구라서.. type 순서나 호출 상황에 따라 다른경우도 생겨서 왠만하면 그냥 바닐라로 쓰거나 ts를 쓰는게 성능을 챙길수있다고 생각합니다

아래는 벤치마크 입니다.

https://www.measurethat.net/Benchmarks/Show/1211/0/map-vs-object

추가로 같은 알고리즘을 비교하는 벤치마크를 해보는 것도 좋을 것 같습니다😁

**Comment by minkj1992** [comment]
@mcauto  처음 js공부할때 map이 왜 필요한지 고민을 했었는데, 결론은 현시점의 퍼포먼스 보다 자바스크립트애서 map을 만든 이유로 접근하자고 결론지었어요(나중에 js에서 더 퍼포먼스를 개선하지 않을까)

추가로 벤치마크를 봤는데 성능테스트가 lookup만으로 비교하기도 했고 4년전 자료인것 같아서, 최신 벤치마크 찾아보는데 [이거](https://stackoverflow.com/a/55711780) 밖에 없는데, 래퍼런스 사이트가 https://jsbench.me/ 여기로 이전되면서 만료 되버린거같네요

**Comment by minkj1992** [comment]
궁금해서 벤치마크(random string 1024* 1024 dummy 넣기)를 만들어봤는데, 

- get, set, has, delete: https://jsben.ch/jfEnr
  - map: object = 100: 63
- set, delete: https://jsben.ch/jXU6z
  - map: object = 100: 83
- set, get, has: https://jsben.ch/J7fyH
  - map: object = 80: 100
- get/set: https://jsben.ch/VE3U9
  - map: object = 95: 100
  
  정도로 퍼포먼스가 나오는거 같네요

**Comment by mcauto** [comment]
오! 벤치마크 공유 감사합니다👍

아무래도 undefined때문에 delete의 performance가 많이 차이나네요 
javascript의 고질적인 문제인 듯합니다. 
삭제하는 작업이 없으면 object가 좋은 것 같아요

추가적으로 테스트코드를 작성해서 알고리즘에서 비교를 돌려보는 것도 공부하는데 좋을 것 같아요!

파이썬은 pytest사용하고 플러그인만 설치하면 동작하는데 
자바스크립트는 안써봐서 잘 모르겠네요😢

**js**  
https://github.com/rogeliog/jest-benchmark  

**python**
https://pypi.org/project/pytest-benchmark/
